# Generated by Django 4.2.29 on 2026-03-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_patientcompanioncheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletado em'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletado em'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
        migrations.AddField(
            model_name='homeservices',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletado em'),
        ),
        migrations.AddField(
            model_name='homeservices',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
        migrations.AddField(
            model_name='patientcompanioncheckin',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletado em'),
        ),
        migrations.AddField(
            model_name='patientcompanioncheckin',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
        migrations.AddField(
            model_name='person',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletado em'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
        migrations.AddField(
            model_name='professionalservices',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletado em'),
        ),
        migrations.AddField(
            model_name='professionalservices',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
    ]
