# Generated by Django 4.2.29 on 2026-03-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_checkin_deleted_at_checkin_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalservices',
            name='beneficiary',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco se o serviço for para a casa (ex: Jardinagem).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services_received', to='people.person', verbose_name='Paciente/Beneficiário'),
        ),
    ]
